export enum VerifyOtpApis{
    VERIFY_EMAIL = 'VERIFY_EMAIL',
    VERIFY_PHONE = 'VERIFY_PHONE',
    FORGOT_PASSCODE = 'FORGOT_PASSCODE',
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    CHANGE_PHONE = 'CHANGE_PHONE',
}