export enum VerifyOtpApis{
    VERIFY_EMAIL = 'VERIFY_EMAIL',
    VERIFY_PHONE = 'VERIFY_PHONE',
    RESET_PASSCODE = 'RESET_PASSCODE',
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    CHANGE_PHONE = 'CHANGE_PHONE',
}