export enum VerifyOtpPurposes {
  VERIFY_EMAIL = "VERIFY_EMAIL",
  VERIFY_PHONE = "VERIFY_PHONE",
  RESET_PASSCODE = "RESET_PASSCODE",
  RESET_EMAIL = "RESET_EMAIL",
  CHANGE_PHONE = "CHANGE_PHONE",
}
